# TensorFlow Dimension

In [ ]:
import tensorflow as tf

sess_config = tf.ConfigProto(gpu_options=tf.GPUOptions(allow_growth=True))

### Dimension과 자주 쓰이는 Constant Value Tensors API를 함께 알아보자

* [Constant Value Tensors](https://www.tensorflow.org/api_guides/python/constant_op#Constant_Value_Tensors)
  * `tf.constant`
  * `tf.zeros`
  * `tf.zeros_like`
  * `tf.ones`
  * `tf.ones_like`
  * `tf.fill`
* Sequences Tensors
  * `tf.linspace`
  * `tf.range`

In [ ]:
# rank 0 tensor: scalar
a = tf.constant(3)

In [ ]:
# rank 1 tensor: vector
b = tf.zeros([2])

In [ ]:
# rank 2 tensor: matrix
c = tf.ones([2, 3])

In [ ]:
# rank 3 tensor: 3-tensor
d = tf.fill([2, 3, 4], 3)

In [ ]:
# ones_like
e = tf.ones_like(d)

In [ ]:
# linespace
f = tf.linspace(1.0, 5.0, 4)

In [ ]:
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)
print(f.shape)

In [ ]:
print(a.name)
print(b.name)
print(c.name)
print(d.name)
print(e.name)
print(f.name)

### `tf.Session()`을 사용하여 값을 출력해보자

In [ ]:
with tf.Session(config=sess_config) as sess:
  print(sess.run(a), '\n')
  print(sess.run(b), '\n')
  print(sess.run(c), '\n')
  print(sess.run(d), '\n')
  print(sess.run(e), '\n')
  print(sess.run(f))

### 여러 변수들 session을 이용하여 한번에 실행

In [ ]:
with tf.Session(config=sess_config) as sess:
  u, v, w, x, y, z = sess.run([a, b, c, d, e, f])
  #print(u, v, w, x, y, z)
  print(u, '\n')
  print(v, '\n')
  print(w, '\n')
  print(x, '\n')
  print(y, '\n')
  print(z)

### 자주 쓰는 Random Tensors 들도 사용해보자

* [Random Tensors](https://www.tensorflow.org/api_guides/python/constant_op#Random_Tensors)
  * `tf.random_normal`
  * `tf.truncated_normal`
  * `tf.random_uniform`
  * `tf.random_shuffle`
  * `tf.random_crop`
  * `tf.multinomial`
  * `tf.random_gamma`
  * `tf.set_random_seed`

In [ ]:
tf.set_random_seed(219)

In [ ]:
g = tf.random_normal([2, 3])
h = tf.random_uniform([2, 3, 4])

In [ ]:
print(g)
print(h)

In [ ]:
print(g.shape)
print(h.shape)

In [ ]:
print(g.name)
print(h.name)

### `tf.Session()`을 사용하여 값을 출력해보자

In [ ]:
with tf.Session(config=sess_config) as sess:
  p, q = sess.run([g, h])
  print(p, '\n')
  print('--------')
  print(q, '\n')

## 직접 실습

### 2D Tensor (matrix) 더하기 및 곱하기

* 2 x 2 random matrix 생성
  * x = [ [1, 2], [3, 4] ]
  * y = [ [5, 6], [7, 8] ]
* elementwise 더하기
* elementwise 곱하기
* matrix 곱하기

In [ ]:
# TODO
x = tf.convert_to_tensor([ [1, 2], [3, 4] ])
y = tf.convert_to_tensor([ [5, 6], [7, 8] ])
# z: elementwise 더하기
z = x + y
# w: elementwise 곱하기
w = x * y
# v: matrix 곱하기
v = tf.matmul(x, y)

with tf.Session(config=sess_config) as sess:
  print(sess.run(x))
  print(sess.run(y))
  print(sess.run(z))
  print(sess.run(w))
  print(sess.run(v))

##### output
```
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
```

### 3D Tensor 단면 자르기
* range를 이용하여 3 x 2 x 2 = 12 element list 생성
* tf.convert_to_tensor 및 tf.reshape을 통해 3D Tensor 변환

In [ ]:
# TODO
#x = list(range(12))
#x = tf.convert_to_tensor(x)
x = tf.range(12)
x = tf.reshape(x, [3, 2, 2])

# index를 이용하여 slice
y = x[0,:,:] + x[2,:,:]

with tf.Session(config=sess_config) as sess:
  print(sess.run(x), '\n')
  print(sess.run(x[0,:,:]), '\n')
  print(sess.run(x[2,:,:]), '\n')
  print(sess.run(y))

##### output
```
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


[[0 1]
 [2 3]]
[[ 8  9]
 [10 11]]
[[ 8 10]
 [12 14]]
```